export { CreatePersonDto } from './create-person.dto'
export { ChangePersonalityDto } from './change-personality.dto'
export { CreateFavouriteColorsDto } from './create-favourite-colors.dto'
export { DeletePersonDto } from './delete-person.dto'
export { GetPersonByYearDto } from './get-person-by-year.dto'
export { GetPersonDto } from './get-person.dto'
